update PHPCS configuration

diff --git a/bin/phpcs b/bin/phpcs
--- a/bin/phpcs
+++ b/bin/phpcs
@@ -57,6 +57,31 @@ function resolveColorStatus() {
   echo "$result"
 }
 
+#
+# Swap report ids "source" and "summary".
+#
+# @param _InOut_ $1 - named reference to the passed report id
+#
+function swapReportIds() {
+  ((BASH_SUBSHELL)) && fail "${FUNCNAME[0]}() can't write to outer scope from subshell"
+  local -n inout="$1"
+  local ids i
+  readarray -t ids < <(printf '%s\n' "${inout//,/$'\n'}")
+
+  for i in "${!ids[@]}"; do                     # swap ids
+    if [[ "${ids[i]}" == 'summary' ]]; then
+      ids[i]='source'
+    elif [[ "${ids[i]}" == 'source' ]]; then
+      ids[i]='summary'
+    elif [[ "${ids[i]}" == '' ]]; then
+      unset 'ids[i]'
+    fi
+  done
+
+  inout=$(printf '%s,' "${ids[@]}")
+  inout="${inout%,}"                            # remove trailing comma
+}
+
 # --- end of functions ---------------------------------------------------------------------------------------------------------------------
 
 
@@ -79,13 +104,26 @@ phpcs="${phpcs#./}"
 [[ -f "$phpcs" ]] || fail "PHPCS executable not found"
 
 
-declare args=() arg showCmd=0
+declare args=() arg
 declare -A options
 options=()
 
 # parse arguments
 while (("$#")); do
   case "$1" in
+    --report|--report=*)
+      arg="${1#--report}"
+      arg="${arg:1}"
+      swapReportIds 'arg'
+      [[ -z "$arg" ]] && fail "missing value for option $1"
+      if [[ -z "${options['--report']:-}" ]]; then
+        options['--report']="--report=$arg"
+      else
+        options['--report']="${options['--report']},$arg"   # concatenate ids of multiple options
+      fi
+      shift
+      continue;;
+
     --standard|--standard=*)
       [[ -n "${options['--standard']:-}" ]] && fail 'multiple --standard options detected'
       arg="${1#--standard}"
@@ -95,18 +133,13 @@ while (("$#")); do
       shift
       continue;;
 
-    --color|--colors)                   # standard and PHPCS syntax
+    --color|--colors)                                       # standard and PHPCS syntax
       options['--color']='--colors'
       shift
       continue;;
 
-    --no-color|--no-colors)             # standard and PHPCS syntax
+    --no-color|--no-colors)                                 # standard and PHPCS syntax
       options['--color']='--no-colors'
-      shift
-      continue;;
-
-    --show-cmd)
-      showCmd=1
       shift
       continue;;
   esac
@@ -115,31 +148,30 @@ while (("$#")); do
 done
 
 
-# prepend the standard to use
+# define the rules to use
 if [[ -z "${options['--standard']:-}" ]]; then
-  defaultRules="$configDir/slevomat.xml"
-  [[ -f "$defaultRules" ]] || fail "file not found \"$defaultRules\""
-  options['--standard']="--standard=$defaultRules"
+  declare rulesFile="$configDir/slevomat.xml"
+  [[ -f "$rulesFile" ]] || fail "file not found \"$rulesFile\""
+  options['--standard']="--standard=$rulesFile"
 fi
-args=("${options['--standard']}" "${args[@]}")
 
 
-# prepend a color option
+# always provide a color option (PHP can't resolve it correctly)
 if [[ -z "${options['--color']:-}" ]]; then
   declare color
-  color="$(resolveColorStatus auto)"              # auto-resolve the current status
+  color="$(resolveColorStatus auto)"                        # auto-resolve the current status
   [[ "$color" == 'on'  ]] && options['--color']='--colors'
   [[ "$color" == 'off' ]] && options['--color']='--no-colors'
 fi
-args=("${options['--color']}" "${args[@]}")
 
 
 # rebuild all arguments
+args=("${options[@]}" "${args[@]}")
 set -- "${args[@]}"
 
 
-# show the final command
-if ((showCmd)); then
+# on DEBUG: show the final command
+if [[ "${DEBUG:-0}" != "0" ]]; then
   declare phpBin=''
   [[ "$php" != 'php' ]] && phpBin="$php "
   echo "CMD: ${phpBin}${phpcs} $*"
