fix PHPStan issues

diff --git a/bin/phpstan b/bin/phpstan
--- a/bin/phpstan
+++ b/bin/phpstan
@@ -1,6 +1,10 @@
 #!/bin/bash
 #
-# A wrapper around PHPStan to simplify working with different versions and/or baseline files. All arguments are optional.
+# A wrapper around PHPStan to simplify switching between multiple PHP and PHPStan versions and/or baseline files.
+# Allows you to optionally use a globally installed PHPStan to keep the "vendor" directory clean of countless
+# Composer dependencies on development tools.
+#
+# All arguments are optional.
 #
 # Usage:
 #   phpstan [COMMAND] [options] [--] [PATH...]
@@ -19,21 +23,48 @@
 # Short option name/value separator are zero or more spaces.      e.g. "-l3" or "-l 4"
 # Long option name/value separator are space or equal sign "=".   e.g. "--level 5" or "--level=6"
 #
-# By default the script looks for a PHPStan binary installed in the "/vendor" directory of the project.
-# If PHPStan was not found in the project the script tries to find a PHPStan binary in the system path.
+# By default the script looks for a PHPStan binary installed in the "vendor" directory of the project.
+# If PHPStan is not installed in the project the script tries to find a globally installed PHPStan.
 # A custom PHPStan binary can be specified by setting the environment variable PHPSTAN='<phpstan-cmd>'.
 #
 # PHPStan can be executed using a custom PHP interpreter by setting the environment variable PHP='<php-cmd>'.
 #
 # Examples:
-#   phpstan                                   // Analyse the code base with the configured settings.
-#   phpstan --level=1 api/app                 // Analyse a single directory with a custom rule level.
-#   phpstan --level=6 -b baseline.neon        // Analyse the code base and save the result as file "baseline.neon".
-#   phpstan --level=7 -u baseline.neon        // Analyse the code base using file "baseline.neon" as a filter.
-#   PHP='php81' phpstan                       // Run PHPStan using PHP command "php81" instead of the standard "php".
-#   PHPSTAN='phpstan-2.0.phar' phpstan        // Run a different PHPStan version instead of the standard installation.
+#   phpstan                                 # Analyse the code base with the configured settings.
+#   phpstan --level=1 api/app               # Analyse a single directory with a custom rule level.
+#   phpstan --level=6 -b baseline.neon      # Analyse the code base and save the result to file "baseline.neon".
+#   phpstan --level=7 -u baseline.neon      # Analyse the code base using file "baseline.neon" as a filter.
+#   PHP=php81 phpstan                       # Use a different PHP version instead of the standard `php`.
+#   PHPSTAN=phpstan-2.1.0.phar phpstan      # Run a different PHPStan version instead of the standard installation.
+#
+#
+# TODO:
+#  - include baseline via dynamic PHP include       @see https://phpstan.org/config-reference#multiple-files
 #
 set -eEuo pipefail
+
+# --- functions ----------------------------------------------------------------------------------------------------------------------------
+
+#
+# Print a message to STDERR and exit the script/subshell.
+#
+# @param $@ - any number of arguments
+#
+function fail() {
+  stderr "$@"
+  exit 127
+}
+
+#
+# Print a message to STDERR but don't exit the script/subshell.
+#
+# @param $@ - any number of arguments
+#
+function stderr() {
+  echo "$@" >&2
+}
+
+# --- end of functions ---------------------------------------------------------------------------------------------------------------------
 
 
 # determine the PHP interpreter to use
@@ -49,13 +80,13 @@ phpstan="${PHPSTAN:-}"
 phpstanCmd="$phpstan"
 
 if [[ -n "$phpstan" ]]; then
-  phpstan="$(type -p "$phpstan")" || { echo "PHPStan executable not found: $phpstanCmd"; exit 1; }
+  phpstan="$(type -p "$phpstan")" || fail "PHPStan executable not found: $phpstanCmd"
 else
   phpstanCmd="vendor/bin/phpstan"
   phpstan="$PROJECT_DIR/$phpstanCmd"
   if [[ ! -f "$phpstan" ]]; then
     phpstanCmd="phpstan" && phpstan="$(type -p "$phpstanCmd")" || {
-      phpstanCmd="phpstan.phar" && phpstan="$(type -p "$phpstanCmd")" || { echo "PHPStan executable not found"; exit 1; }
+      phpstanCmd="phpstan.phar" && phpstan="$(type -p "$phpstanCmd")" || fail "PHPStan executable not found"
     }
   fi
 fi
@@ -138,15 +169,15 @@ USE_DEFAULT=
 
 # validate config options
 if [[ -n "$CONFIG_OPTION" ]]; then
-    [[ -z "$CONFIG_FILE" ]] && { echo "Option $CONFIG_OPTION needs a value"; exit 1; }
-    [[ -f "$CONFIG_FILE" ]] || { echo "Config file \"$CONFIG_FILE\" not found"; exit 1; }
+    [[ -z "$CONFIG_FILE" ]] && fail "Option $CONFIG_OPTION needs a value"
+    [[ -f "$CONFIG_FILE" ]] || fail "Config file \"$CONFIG_FILE\" not found"
 else
    FILES=('phpstan.neon' 'phpstan.neon.dist' 'phpstan.dist.neon')
    for file in "${FILES[@]}"; do
        file="$CONFIG_DIR/$file"
        [[ -f "$file" ]] && CONFIG_FILE="$file" && break
    done
-   [[ -z "$CONFIG_FILE" ]] && { echo "No config file found in \"$CONFIG_DIR\""; exit 1; }
+   [[ -z "$CONFIG_FILE" ]] && fail "No config file found in \"$CONFIG_DIR\""
 fi
 ((IS_WINDOWS_PHP)) && CONFIG_FILE="$(cygpath -m "$CONFIG_FILE")"                # normalize path if running a Windows PHP version
 
@@ -158,8 +189,8 @@ if [[ -n "$BASELINE_OPTION" ]]; then
     ARGS=("$BASELINE_OPTION" "${ARGS[@]}")
   else
     # validate baseline option
-    [[ -z "$BASELINE_FILE" ]] && { echo "Option $BASELINE_OPTION needs a value"; exit 1; }
-    [[ -f "$BASELINE_FILE" ]] || { echo "Baseline file \"$BASELINE_FILE\" not found"; exit 1; }
+    [[ -z "$BASELINE_FILE" ]] && fail "Option $BASELINE_OPTION needs a value"
+    [[ -f "$BASELINE_FILE" ]] || fail "Baseline file \"$BASELINE_FILE\" not found"
 
     INCLUDE_CONFIG="$(mktemp --suffix .neon include.XXX)"                       # create tmp file and register it for automatic deletion
     trap "rm -f '$INCLUDE_CONFIG'" EXIT
