update PHPStan wrapper

diff --git a/bin/phpstan b/bin/phpstan
--- a/bin/phpstan
+++ b/bin/phpstan
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Conveniant wrapper of PHPStan. Sets default values and adds command-line support for using baseline files
+# Conveniant wrapper for PHPStan. Sets default values and adds command-line support for using baseline files
 # (a feature PHPStan lacks). Also supports switching between multiple PHP and/or PHPStan versions.
 #
 # Usage:                                    All arguments are optional.
@@ -38,7 +38,7 @@
 # TODO:
 #  - include baseline via dynamic PHP include           @see https://phpstan.org/config-reference#multiple-files
 #
-# @version 2025.07.26 21:25
+# @version 2025.08.11 18:08
 #
 set -eEuo pipefail
 
@@ -46,6 +46,7 @@ exec 3>&1                                                       # duplicate orig
 
 
 # --- functions ----------------------------------------------------------------------------------------------------------------------------
+
 
 #
 # Print a message to STDERR and exit the script/subshell.
@@ -57,6 +58,7 @@ function fail() {
   exit 127
 }
 
+
 #
 # Print a message to STDERR but don't exit the script/subshell.
 #
@@ -65,6 +67,37 @@ function fail() {
 function stderr() {
   echo "$@" >&2
 }
+
+
+#
+# Read configuration files in isolation and extract the requested variables.
+#
+# @param _InOut_ $1 - named reference to an associative array holding the resulting configuration
+# @param _In_    $2 - named reference to an array holding the configuration files to read
+# @param _In_    $@ - any number of variable names to extract from the configuration
+#
+function readConfig() {
+  ((BASH_SUBSHELL)) && fail "${FUNCNAME[0]}() can't write to outer scope from subshell"
+  local -n _config="$1"
+  local -n _files="$2"
+  ((!${#_files[@]})) && fail "${FUNCNAME[0]}() invalid argument '$2' (empty array)"
+  shift 2
+  ((!"$#")) && fail "${FUNCNAME[0]}() missing variable names (empty)"
+  local key value
+
+  while IFS='=' read -r key value; do
+    _config["$key"]="$value"
+  done < <(
+    unset "$@"
+    for file in "${_files[@]}"; do
+      [[ -f "$file" ]] && source "$file" &> /dev/null
+    done
+    for var in "$@"; do
+      [[ -v "$var" ]] && echo "$var=${!var}"
+    done
+  )
+}
+
 
 #
 # Whether to colorize the output in the current context.
@@ -85,36 +118,51 @@ function useColors() {
   return $((!color))
 }
 
+
 # --- end of functions ---------------------------------------------------------------------------------------------------------------------
 
 
-# determine the PHP interpreter to use
-declare php="${PHP:-php}"
+# ensure we run Bash v4.3+
+((BASH_VERSINFO[0] < 4 || (BASH_VERSINFO[0] == 4 && BASH_VERSINFO[1] < 3))) && fail "this script requires Bash version 4.3+"
 
 
 # resolve the project root directory
-declare isWindowsPhp projectDir
-isWindowsPhp="$("$php" -r "echo (int)(PHP_OS_FAMILY == 'Windows');")"
+declare projectDir
 projectDir="$(realpath --relative-to=. "$(dirname "$(realpath "$(type -p "$0")")")"/..)"
+
+
+# read the configuration
+declare -A config; config=()
+declare files=("$projectDir/.env.dist" "$projectDir/.env") exportVars=()
+readConfig 'config' 'files'  PHP  PHP_COMPOSER_VENDOR_DIR  PHPSTAN  PHPSTAN_EXPORT_VARS
+
+[[ -v PHP                     ]] || PHP="${config[PHP]:-}"
+[[ -v PHP_COMPOSER_VENDOR_DIR ]] || PHP_COMPOSER_VENDOR_DIR="${config[PHP_COMPOSER_VENDOR_DIR]:-}"
+[[ -v PHPSTAN                 ]] || PHPSTAN="${config[PHPSTAN]:-}"
+
+IFS=$' \t' read -ra exportVars <<< "${config[PHPSTAN_EXPORT_VARS]:-}"
+((${#exportVars[@]})) && {
+  readConfig 'config' 'files' "${exportVars[@]}"
+  for var in "${exportVars[@]}"; do
+    [[ -v "$var" ]] || declare "$var"="${config[$var]:-}"
+  done
+}
+
+
+# determine the PHP interpreter to use
+declare php="${PHP:-php}" isWindowsPhp
+isWindowsPhp="$("$php" -r "echo (int)(PHP_OS_FAMILY == 'Windows');")"
 [[ "$projectDir" == /* ]] && ((isWindowsPhp)) && projectDir="$(cygpath -m "$projectDir")"
 
 
-# source an existing env configuration
-declare files=('.env.dist' '.env') file
-for file in "${files[@]}"; do
-  [[ -f "$projectDir/$file" ]] && . "$projectDir/$file"
-done
-
-
-# resolve config and vendor directory
-declare configDir="$projectDir/etc/phpstan" configFile=''
-configDir="${configDir#./}"
-declare vendorDir="$projectDir/${PHP_COMPOSER_VENDOR_DIR:-vendor}"
+# resolve vendor and config directory
+declare vendorDir="$projectDir/${PHP_COMPOSER_VENDOR_DIR:-vendor}" configDir="$projectDir/etc/phpstan" configFile=''
 vendorDir="${vendorDir#./}"
+configDir="${configDir#./}"
 
 
 # determine the PHPStan executable to use
-declare PHPSTAN="${PHPSTAN:-}" phpstan phpstanCmd isExternalPhpstan=0
+declare phpstan phpstanCmd isExternalPhpstan=0
 
 if [[ -n "$PHPSTAN" ]]; then                                    # a user-specified command
   phpstanCmd="$PHPSTAN"
@@ -134,10 +182,9 @@ fi
 ((isWindowsPhp)) && phpstan="$(cygpath -m "$phpstan")"
 
 
-# parse command line arguments
-declare args=() arg cmd=''                                      # symfony/console (and thus PHPStan) supports:
-declare -A options                                              # -s[ ]VALUE             - optional space separator
-options=()                                                      # --long-option[= ]VALUE - mandatory equal or space separator
+# parse command line arguments                                  # symfony/console (and thus PHPStan) supports:
+declare -A options; options=()                                  # -s[ ]VALUE             - optional space separator
+declare args=() arg cmd=''                                      # --long-option[= ]VALUE - mandatory equal or space separator
 
 
 # extract and set the PHPStan command
@@ -274,7 +321,7 @@ else
   options['--memory-limit']="--memory-limit=${options[--memory-limit]}"
 fi
 
-# --color (PHP can't resolve it correctly)
+# --color: PHP can't resolve it correctly
 if [[ -z "${options['--color']:-}" ]]; then
   useColors && options['--color']='--ansi' || options['--color']='--no-ansi'
 fi
@@ -311,6 +358,10 @@ fi
 # rebuild all arguments
 args=("$cmd" "${options[@]}" "${args[@]+"${args[@]}"}")
 set -- "${args[@]}"
+
+
+# export vars
+((${#exportVars[@]})) && export "${exportVars[@]}"
 
 
 # on DEBUG: show the final command
